return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  event = 'BufReadPost',
  dependencies = {
    'windwp/nvim-ts-autotag',
    'RRethy/nvim-treesitter-endwise',
    'JoosepAlviste/nvim-ts-context-commentstring',
    'nvim-treesitter/nvim-treesitter-textobjects',
  },
  config = function()
    require('nvim-treesitter.configs').setup({
      highlight = {
        enable = true,
        use_languagetree = true
      },
      ensure_installed = {
        'bash',
        'c',
        'cpp',
        'css',
        'diff',
        'fish',
        'gitignore',
        'go',
        'graphql',
        'help',
        'html',
        'http',
        'java',
        'javascript',
        'jsdoc',
        'jsonc',
        'latex',
        'lua',
        'markdown',
        'markdown_inline',
        'meson',
        'ninja',
        'nix',
        'norg',
        'org',
        'php',
        'python',
        'query',
        'regex',
        'rust',
        'scss',
        'sql',
        'svelte',
        'teal',
        'toml',
        'tsx',
        'typescript',
        'vhs',
        'vim',
        'vue',
        'wgsl',
        'yaml',
        'json',
      },
      endwise = {
        enable = true,
      },
    })
    require('nvim-ts-autotag').setup()
  end
}
