add_newline = false

format = "$username$hostname$python$directory$character"
right_format = "$cmd_duration$status$git_branch$git_status"

[username]
show_always = false
format = "[$user]($style)"
style_user = "green"
style_root = "bold red"

[hostname]
ssh_only = true
format = "@[$hostname]($style) "
style = "yellow"

[python]
format = '[(\($virtualenv\) )]($style)'
style = "cyan"

[directory]
style = "blue"
format = "[$path]($style) "
fish_style_pwd_dir_length = 1
truncation_length = 1
truncate_to_repo = false

[character]
success_symbol = "[❯](red)[❯](yellow)[❯](green)"
error_symbol = "[❯❯❯](red)"

[git_branch]
format = "[$branch]($style) "
style = "green"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "yellow"

[status]
disabled = false
format = "[✘ $status]($style) "
style = "red"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
